defmodule Fester.Repo.Migrations.CreateUtxos do
  use Ecto.Migration

  def change do
    # Must be enabled for the hash function to work
    execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;", "DROP EXTENSION IF EXISTS pgcrypto;")

    create_if_not_exists table(:utxos, primary_key: false) do
      add :utxo_ref, :string, primary_key: true
      # Some Byron era addresses are huge so we must use text
      # instead of string (varchar 255)
      add :address, :text, null: false
      # Hash of the address is needed for the index. PG has an index limit of 8KB
      # and some Byron addresses are too long to fit in the index.
      # This field is auto-generated by database trigger from the address field
      add :address_hash, :string, null: false
      add :value, :jsonb, null: false, default: "{}"
      add :created_at_slot, :integer, null: false
      add :consumed_at_slot, :integer, null: true
      # Normally we'd use timestamps() here but since we are using Repo.insert_all,
      # we need to use explicit timestamp fields so we can use a default value for these fields
      # and avoid having to manually set them in Elixir code.
      add :inserted_at, :naive_datetime, null: false, default: fragment("now()")
      add :updated_at, :naive_datetime, null: false, default: fragment("now()")
    end

    execute(
      """
      CREATE OR REPLACE FUNCTION generate_address_hash() RETURNS TRIGGER AS $$
      BEGIN
        NEW.address_hash = encode(digest(NEW.address, 'sha256'), 'hex');
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
      """,
      "DROP FUNCTION IF EXISTS generate_address_hash();"
    )

    execute(
      """
      CREATE TRIGGER utxos_generate_address_hash_trigger
        BEFORE INSERT OR UPDATE ON utxos
        FOR EACH ROW
        EXECUTE FUNCTION generate_address_hash();
      """,
      "DROP TRIGGER IF EXISTS utxos_generate_address_hash_trigger ON utxos;"
    )

    create_if_not_exists index(:utxos, [:address_hash, :consumed_at_slot],
                           where: "consumed_at_slot IS NULL"
                         )

    create_if_not_exists index(:utxos, [:created_at_slot])
    create_if_not_exists index(:utxos, [:consumed_at_slot, :created_at_slot])
  end
end
